#--------------outputs.py--------------#
""" Στο αρχείο αυτό βρίσκονται όλες οι συναρτήσεις και οι μέθοδοι που εμφανίζουν
στην οθόνη την πρόοδο του παιχνιδιού."""

def welcome_message():
    """Εμφανίζει ένα μήνυμα στην οθόνη του υπολογιστή, δεν επιστρέφει κάποια τιμή."""
    print('╔════════════════════════════╗')
    print('║     ΚΡΕΜΑΛΑ:THE PC GAME    ║')
    print('╚════════════════════════════╝')
    print('Το κλασσικό παιχνίδι της "Κρεμάλας" στον υπολογιστή σας!')
    print('Ας ξεκινήσουμε!')

def round_message(n):
    print('══════════════════════════════')
    print('┌─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┐')
    print('         Γύρος #'+str(n)+'    ')    
    print('└─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ┘')
    print('══════════════════════════════')

def show_hangingman(lives_left,difficulty):
    """Ανάλογα με τις ζωές του χρήστη (και το επίπεδο δυσκολίας που επέλεξε) , εμφανίζει τα στάδια της κρεμάλας"""
    if difficulty=='Αρχάριος':
        if lives_left==0:
            print('|---------|')
            print('|         Ο')
            print('|        /|\\')
            print('|         |')
            print('|       _/ \_')
            print('|       ## ##')
            print('|        fire')
        elif lives_left==1:
            print('|---------|')
            print('|         Ο')
            print('|        /|\\')
            print('|         |')
            print('|       _/ \_')
            print('|       ## ##')
            print('|')
        elif lives_left==2:
            print('|---------|')
            print('|         Ο')
            print('|        /|\\')
            print('|         |')
            print('|       _/ \_')
            print('|')
            print('|')
        elif lives_left==3:
            print('|---------|')
            print('|         Ο')
            print('|        /|\\')
            print('|         |')
            print('|          \_')
            print('|')
            print('|')
        elif lives_left==4:
            print('|---------|')
            print('|         Ο')
            print('|        /|\\')
            print('|         |')
            print('|')
            print('|')
            print('|')
        elif lives_left==5:
            print('|---------|')
            print('|         Ο')
            print('|         |\\')
            print('|         |')
            print('|')
            print('|')
            print('|')
        elif lives_left==6:
            print('|---------|')
            print('|         Ο')
            print('|         |')
            print('|         |')
            print('|')
            print('|')
            print('|')
        elif lives_left==7:
            print('|---------|')
            print('|         Ο')
            print('|')
            print('|')
            print('|')
            print('|')
            print('|')
            print('|')
    elif difficulty=='Μέτριος':
        if lives_left==0:
            print('|---------|')
            print('|         Ο')
            print('|        /|\\')
            print('|         |')
            print('|       _/ \_')
            print('|       ## ##')
            print('|        fire')
        elif lives_left==1:
            print('|---------|')
            print('|         Ο')
            print('|        /|\\')
            print('|         |')
            print('|       _/ \_')
            print('|       ## ##')
            print('|')
        elif lives_left==2:
            print('|---------|')
            print('|         Ο')
            print('|        /|\\')
            print('|         |')
            print('|       _/ \_')
            print('|')
            print('|')
        elif lives_left==3:
            print('|---------|')
            print('|         Ο')
            print('|        /|\\')
            print('|         |')
            print('|')
            print('|')
            print('|')
        elif lives_left==4:
            print('|---------|')
            print('|         Ο')
            print('|         |')
            print('|         |')
            print('|')
            print('|')
            print('|')
        elif lives_left==5:
            print('|---------|')
            print('|         Ο')
            print('|')
            print('|')
            print('|')
            print('|')
            print('|')
    elif difficulty=='Έμπειρος':
        if lives_left==0:
            print('|---------|')
            print('|         Ο')
            print('|        /|\\')
            print('|         |')
            print('|       _/ \_')
            print('|       ## ##')
            print('|        fire')
        elif lives_left==1:
            print('|---------|')
            print('|         Ο')
            print('|        /|\\')
            print('|         |')
            print('|       _/ \_')
            print('|       ## ##')
            print('|        ')
        elif lives_left==2:
            print('|---------|')
            print('|         Ο')
            print('|        /|\\')
            print('|         |')
            print('|       _/ \_')
            print('|')
            print('|')
        elif lives_left==3:
            print('|---------|')
            print('|         Ο')
            print('|         |')
            print('|         |')
            print('|')
            print('|')
            print('|')
